
spring:
  datasource:
    password: wolly2024
    url: jdbc:mysql://127.0.0.1:3307/admin_app
    username: root
  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
  mvc:
    log-request-details: true
logging:
  level:
    org:
      springframework:
        security: DEBUG